name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/included
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run E2E tests
        run: npx cypress run
